apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-demo
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: ecf-bancack-back
          image: 071170175291.dkr.ecr.us-west-2.amazonaws.com/studi/ecf_bancask_back:latest
          ports:
            - containerPort: 3000